# Currently Active Working Groups / Committees 

The following describe currently active working groups listed in alphabetical
order. If you are interested in becoming involved with one of these groups
please contact the group leader(s) on [Bioconductor Zulip](https://chat.bioconductor.org) .


## BiocAsia

- Description: This group will primarily be involved with conference planning for the BiocAsia conference and seeks to formalise this as a Bioconductor Working Group
- Zulip: #biocasia-conference-organization, #biocasia
- Leads: Stevie Pederson, Stefano Mangiola
- Current Members: Stevie Pederson, Stefano Mangiola, Ellis Patrick, Kozo Nishida, Malvika Kharbanda, Mansi Aggarwal, Zuguang Gu, Maria Doyle, Lori Shepherd

## Classes and Methods Recommendations

- Description: Discussions arounnd Bioconductor 'official' classes and methods
  and how to articulate their benefits to increase their usage across the
  ecosystem, in particular in new contributions. Contemplation of how to
  integrate S7 framework.
- Zulip: #biocclasses
- Links: https://github.com/Bioconductor/BiocClassesWorkingGroup
- Leads: Michael Lawrence, Dario Righelli, Lori Shepherd
- Current Members: Vince Carey, Laurent Gatto, Michael Lawrence, Marcel Ramos,
  Lluis Revilla, Dario Righelli, Lori Shepherd, Malte Thodberg, Tim Triche  

## Code of Conduct

- Description: The Code of Conduct Committee reviews and revises the
  Bioconductor Code of Conduct as needed. There is also a large effort to
  translate the Code of Code to multiple languages.
- Links: https://github.com/Bioconductor/bioc_coc_multilingual
- Zulip: private channel
- Leads: Anna Quaglieri, Gerry Tonkin-Hill
- Current Members: Kevin Rue-Albrecht, Martin Davila-Cervantes, Federica
  Gazzelloni, Michael Love, Federico Marini, Sowmya Parthiban, Shixiang Wang,
  Lluis Revilla, Paulina Boadiwaa Mensah, Peace Sandy, Sinmisoluwa Adesanya,
  Michella Savage

## Conference Planning

- Description: Organizes and Plans the Annual Conference.
- Zulip: #bioc-conference-organization, #bioc-conference-everyone
- Leads: Erica Feick
- Current Members: Charlotte Soneson, Jenny D, Jenny S, Lori, Marc, Andrew, Daniela, Matt, Mikhail, Samuel, Krithika, Sean, Wes

## EDAM collaboration

- Description: This group unites EDAM and Bioconductor community members to explore indexing the Bioconductor ecosystem using the [EDAM ontology](https://edamontology.org/). Our working group's objectives include increasing the visibility of Bioconductor packages to a broader audience, including those not primarily using R, and expanding EDAM as a standard for annotating computational biology resources. Through this collaboration, we aim to synergize two large, international communities focused on open science. Future plans may include exploring connections with bio.tools, Bioschemas, and TeSS. If you're interested in contributing or want to learn more, join us on [Bioconductor Zulip](https://chat.bioconductor.org).
- Zulip: #edam-collaboration
- Leads: Claire Rioualen, Maria Doyle, Hervé Pagès
- Current Members: Vince Carey, Hervé Menager, Lori Shepherd, Johannes Rainer, Kozo Nishida, Matúš Kalaš

## FAIR data sharing

- Description: FAIR is defined as Findable, Accessible, Interoperable, and Reusable. This group aims to help users share Bioconductor objects in a way that is interoperable and reusable across language and over time. This group will work on recommendations and documentation/workshops that discuss the pros and cons of various alternatives to saving with base R, e.g. save() and saveRDS(), aimed at beginner Bioconductor users. It will also discuss future directions of software projects within Bioconductor and from other open source communities, related to sharing rich datasets.
- Zulip: `#fair-data-sharing`
- Leads: Michael Love, Kevin Rue-Albrecht
- Current Members: Michael Love, Kevin Rue-Albrecht, Jayaram Kancherla, Lori Shepherd

## Hackathon Planning

- Description: Committee for planning recurring Bioconductor related hack-a-thon / code-a-thon events. 
- Zulip: #hackathon-planning
- Leads: Nicholas Cooley, Lori Kern
- Current Members: Maria Doyle, Kevin Rue-Albrecht, Helena Crowell, Laurent Gatto, Lluis Revilla

## Mass Spectrometry for Proteomics and Metabolomics

- Description: The goal of this working group is to identify members of the
  Bioconductor community that are interested and/or active in the area of mass
  spectrometry, proteomics and/or metabolomics and define technical needs or
  community expectations to prioritise future developments.
- Links: https://github.com/lgatto/BiocMassSpecWorkingGroup
- Zulip: #mass-spectrometry, #metabolomics, #proteomics
- Leads: Laurent Gatto and Johannes Rainer (CAB) 
- Current Members: Laurent, Johannes. 

## Microbiome

- Description: This working group aims to faciliate collaboration in microbiome data science.
- Zulip: #miaverse
- Leads: Tuomas Borman
- Current Members: Tuomas, participation of other members is yet to be confirmed. An informal Bioconductor working group for the microbiome project has already been active and may serve as a basis for this initiative.

## Multilingual

- Description: The multiligual group is focused on translating and hosting
  Bioconductor material in multiple languages. Help is always appreciated!
- Zulip: #documentation-translation

### Code of Conduct Translation  
- Links: [CoC](https://github.com/Bioconductor/bioc_coc_multilingual), [talks_and_transcripts](https://github.com/BioconductorBoards/CABWorkingGroups/tree/main/talks_and_transcripts)
- Leads: Leonardo Collado-Torres, Kozo Nishida, Daniela Cassol, Kevin Rue-Albrecht, Dario Righelli.

### French Translation Subgroup
- Description: Focused on translating Bioconductor Carpentries lessons into French.
- Current Members: Marie Hidjo (co-lead), Laurent Gatto (co-lead), Susan Holmes, Laura Symul.
- Zulip:  #translation-fr

### Spanish Translation Subgroup
- Description: Focused on translating Bioconductor Carpentries lessons into Spanish.
- Leads: Robert Castelo (lead), Javier Carpinteyro Ponce
- Current Members:
- Zulip:  #translation-es

## Multi-omic Integration of Histopathology Image Analysis

- Description: This working group addresses the need for standardized workflows
  to integrate histopathology image-derived features with genomic and
  transcriptomic analyses in R/Bioconductor. We will develop data structures and
  workflows for processing image analysis outputs, create a curated repository
  of TCGA image features, and provide comprehensive training resources. Initial
  goals: For the next two years, we plan to establish standardized workflows for
  importing image features from Python-based tools into R/Bioconductor data
  structures, process TCGA histopathology images and create a curated repository
  of extracted features, and develop educational materials and documentation for
  integrated image-omic analysis.
- Leads: Sehyun Oh
- Current Members: Mohamed Omar, Ilaria Billato, Hervé Pagès, Levi Waldron,
  Davide Risso, Chiara Romualdi, Luigi Marchionni, Marcel Ramos, Sean Davis,
  Lucio Queiroz
- Zulip: #histopathology-image-anlyasis

## Package Build Report Triage

- Description: This committee would be responsible for reaching out to ERRORing
  package maintainers to fix their package and identify inactive packages for
  deprecation. While we have autonotificaiton of failure, many (most)
  maintainers ignore and are not good about checking the provided build
  reports. The core team has found that sending personalized emails greatly
  increases the likelihood of a maintainer to fix the package.
- Links: https://bioconductor.org/checkResults/
- Leads: Lori Shepherd <Lori.Shepherd@RoswellPark.org> 
- Current Members: I need more members! Please email or contact on Zulip if interested

## Package Reviews

- Description: Bioconductor review process of incoming packages is an open
  review process. Bioconductor relies on trained volunteers to review in coming
  packages to ensure adherence to Bioconductor package guidelines. We are always
  in need of more package reviewers.
- Links: [Package Reviewers](https://bioconductor.org/about/package-reviewers/),
  [Contribution Guidelines](https://contributions.bioconductor.org/),
  [Submission Queue](https://github.com/Bioconductor/Contributions/issues)
- Zulip: #package-submission, #reviewers
- Leads: Lori Shepherd <Lori.Shepherd@RoswellPark.org> 
- Current Members: Helena Crowell, Peter Hickey, Kayla Interdonato, Jianhong Oh,
  Herve Pages, Marcel Ramos, Mireia Ramos-Rodriguez, Jacques Serizay, Dario
  Strbenac

## R-Ladies and Bioc

- Description: The R-Ladies working group aims to foster collaboration between Bioconductor
  and R-Ladies to encourage, support, and promote gender minorities at the
  intersection of computational biology/bioinformatics and data science. We will
  achieve this through co-hosted events, blog posts, and other collaborative initiatives.
- Links:
- Zulip: #r-ladies
- Leads: Janani Ravi
- Current Members: Janani Ravi, Daniela Cassol, Aedin Culhane, Lori Shepherd,
  Stephanie Hicks, Heather Turner

## Social Media

- Description: Group for creating Bioconductor strategy, guidelines etc for social media (Blog, Twitter, Mastodon, YouTube, LinkedIn, Instagram, TikTok, Bilibili, WeChat, Weibo...).
- Links: 
- Zulip: #social-media
- Leads: Maria Doyle
- Current Members: Laurent Gatto, Susan Holmes, Federica Gazzelloni, İrem Kahveci, Hamdi Furkan Kepenek, Xueyi Dong, Shixiang Wang, Kozo Nishida

## Spatial (Transcript)omics

- Description: We hope to discuss, identify, and coordinate efforts to address
  current and prospective technical needs around spatial omics; e.g.,
  standardized and language-agnostic file formats, cross-framework and -language
  interoperability, handling data across modalities and coordinate systems,
  visualization etc.
- Links: 
- Zulip: #spatial #spatial-interoperability #spatialdata-devel #image-analysis
- Lead: Helena Crowell
- Members: Artür Manukyan, Ellis Patrick, Dario Righelli, Davide Risso, Gabriel Grajeda, Ludwig Geistlinger, Ludwig Geistlinger, Lukas Weber, Mark Robinson, Martin Emons, Phillip Nicol, Samuel Gunz, Shila Ghazanfar, Stephanie Hicks, Yixing Estella Dong

## Student - ECR Council

- Description: This groups seeks to represent students and early career researchers both already in the Bioconductor community and those who might be interested but have not joined yet
- Zulip: #student-ecr
- Leads: Carissa Chen, Guillaume Deflandre, Jasper Spitzer, Sophie-Marie Wind
- Founding Members: Carissa Chen, Guillaume Deflandre, Jasper Spitzer, Sophie-Marie Wind
- Current Members: Open to all, please reach out in the Zulip Channel! We also have an email address where were happy to recieve any input: student-ecr@bioconductor.org!

## TeSS

- Description: This group focuses on enhancing the connectivity and integration between the [TeSS (Training eSupport System)](https://tess.elixir-europe.org) portal and the Bioconductor project. Our objectives include implementing Bioschemas for Bioconductor training material and events to improve their discoverability and accessibility via TeSS (https://tess.elixir-europe.org/content_providers/bioconductor). We aim to strengthen the bridge between these platforms, facilitating easier access to Bioconductor training resources.
- Zulip: #tess-integration
- Leads: Maria Doyle
- Current Members: Maria Doyle, Laurent Gatto (contact Maria on Zulip if interested to join this initiative)

## Training

- Description: The Bioconductor training committee is a collaborative effort to consolidate Bioconductor-focused training material and establish a community of Bioconductor trainers. We define a curriculum and implement online lessons for beginner and more advanced R users who want to learn to analyse their data with Bioconductor packages.
- Links: https://training.bioconductor.org
- Zulip: #education-and-training
- Leads: Laurent Gatto, Charlotte Soneson, Kevin Rue-Albrecht
- Founding Members: Laurent Gatto, Charlotte Soneson, Kevin Rue-Albrecht, Jenny Drnevich, Robert Castelo, Toby Hodges, Susan Holmes
- Current Members: Open to all. Join us! Details [here](https://www.bioconductor.org/help/education-training/).

## Workflows

- Description: This group is focussed on updating and rebranding Bioconductor Workflows as well as streamlining arrangements with an external publisher, specifically for workflows. 
- Links:
- Zulip: #workflows
- Leads: Michael Love
- Current Members: Charlotte Soneson, Davide Risso, Lori Shepherd, Stevie Pederson, Susan Holmes, Ellis Patrick, Sean Davis, Aedin Culhane, Vince Carey, Janani Ravi, Woflgang Huber
